version: '2'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: ss3_server
    ports:
      - "80:80"
    environment:
      APP_ENV: dev
    volumes:
      - .:/var/www
    networks:
      - ss3net
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "ss3_db"
    ports:
      - "3306:3306"
    volumes:
      - ss3mysqldata:/var/lib/mysql
    networks:
      - ss3net
networks:
  ss3net:
    driver: bridge
volumes:
  ss3mysqldata:
    driver: local
